name: Github Docker CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nginx_version: ['1']
        os_type: ['alpine']
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action@v1.0.3

      - name: Set Environment Variables
        env:
          DOCKER_IMAGE: nginx:${{ matrix.nginx_version }}-${{ matrix.os_type }}
          IMAGE_TAG_LATEST: noitran/nginx:${{ matrix.os_type }}-latest
        run: |
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "image_tag_latest=${IMAGE_TAG_LATEST}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          mkdir dist
          sed -e "s/%%DOCKER_IMAGE%%/${{ env.docker_image }}/g" Dockerfile.template > ./dist/Dockerfile
          docker build -f ./dist/Dockerfile . -t ${{ env.image_tag_latest }}
          docker image ls

      - name: Test image which was built
        if: success()
        run: |
          dgoss run -t ${{ env.image_tag_latest }}

      - name: Push image to Docker hub
        if: success()
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ env.image_tag_latest }}
          docker logout
